language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

before_script:
  - mysql -uroot -e "create database IF NOT EXISTS watchdog;"
  - mysql -uroot watchdog < database.sql

script:
  - make install
  - make qa
