language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

before_script:
  - mysql -uroot -e "create database IF NOT EXISTS watchdog;"
  - mysql -uroot watchdog < database.sql

script:
  - make install
  - make qa

after_success:
  - bash <(curl -s https://codecov.io/bash)
