CREATE TABLE logs (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(50) NOT NULL,
    http_code SMALLINT UNSIGNED NOT NULL,
    total_time FLOAT(8, 6) UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
